[tool.poetry]
name = "yolov8_csis"
version = "0.1.0"
description = ""
authors = ["Formas"]

[tool.poetry.dependencies]
python = ">=3.10"
python-multipart = "*"
numpy = "*"
fastapi = "*"
uvicorn = "*"
asyncio = "*"
firebase-admin = "*"
dynaconf = "*"

[tool.poetry.dev-dependencies]
ultralytics = "*"